### ISSUE TITLE
Implement new robotic parts

### ISSUE THREAD

**Issue by JonnyNova** [rimworld-frontierdevelopment/Rimworld-Cyberization#3]
### Research

- [x] Robotic Prosthetics (Industrial, 1500; requires: Machining, Prosthetics)

### Parts

- [x] Robotic eye
- [x] Robotic arm
- [x] Robotic hand
- [x] Robotic leg
- [x] Robotic jaw

**Comment by jetpack-maniac** [comment]
No parts and research are complete.
